name: Release Provenance
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      subject-path:
        required: true
        type: string
permissions:
  actions: read
  attestations: write
  contents: read
  id-token: write
jobs:
  provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.artifact-name }}
      - uses: actions/attest@a1948c3f048ba23858d222213b7c278aabede763 # v4
        with:
          subject-path: ${{ inputs.subject-path }}
          show-summary: true
